### ISSUE TITLE
ValueError: No cuda/mps available.

### ISSUE THREAD

**Issue by My12123** [vosen/ZLUDA#53]
```python
(venv) F:\nunif>F:\nunif\zluda-2-windows\zluda_with.exe -- python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400 -g 1
Traceback (most recent call last):
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nunif\waifu2x\web\__main__.py", line 9, in <module>
    from .server import main
  File "F:\nunif\waifu2x\web\server.py", line 154, in <module>
    command_args, config, art_ctx, art_scan_ctx, photo_ctx, cache, cache_gc = setup()
  File "F:\nunif\waifu2x\web\server.py", line 131, in setup
    art_ctx = Waifu2x(model_dir=args.art_model_dir, gpus=args.gpu)
  File "F:\nunif\waifu2x\utils.py", line 23, in __init__
    self.device = create_device(gpus)
  File "F:\nunif\nunif\device.py", line 21, in create_device
    return torch.device(create_device_name(device_id))
  File "F:\nunif\nunif\device.py", line 16, in create_device_name
    raise ValueError("No cuda/mps available. Use `--gpu -1` for CPU.")
ValueError: No cuda/mps available. Use `--gpu -1` for CPU.
```

**Comment by vosen** [comment]
Closing because no longer relevant.
Feel free to open a new issue if it applies to the new version
