### ISSUE TITLE
[Bug]: fails to build ZLUDA.

### ISSUE THREAD

**Issue by lshqqytiger** [vosen/ZLUDA#76]
I can't build ZLUDA from source on Windows.

# Versions
Git 2.42.0.windows.2
CMake 3.28.0
Python 3.10.13
Rust 1.76.0 (07dca489a 2024-02-04)
AMD Radeon Software: Pro Edition 23.Q4 (2023/11/22)
Ninja 1.11.1

# Full log
```
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling serde v1.0.196
   Compiling thiserror v1.0.57
   Compiling camino v1.1.6
   Compiling semver v1.0.21
   Compiling serde_json v1.0.113
   Compiling itoa v1.0.10
   Compiling ryu v1.0.16
   Compiling quote v1.0.35
   Compiling syn v2.0.48
   Compiling serde_derive v1.0.196
   Compiling thiserror-impl v1.0.57
   Compiling argh_shared v0.1.12
   Compiling cargo-platform v0.1.5
   Compiling argh_derive v0.1.12
   Compiling cargo_metadata v0.17.0
   Compiling argh v0.1.12
   Compiling xtask v0.0.0 (E:\ML\zluda\xtask)
    Finished dev [unoptimized + debuginfo] target(s) in 10.21s
     Running `target\debug\xtask.exe --release`
   Compiling proc-macro2 v1.0.78
   Compiling unicode-ident v1.0.12
   Compiling jobserver v0.1.28
   Compiling version_check v0.9.4
   Compiling syn v1.0.109
   Compiling serde v1.0.196
   Compiling pkg-config v0.3.29
   Compiling windows_x86_64_msvc v0.48.5
   Compiling winapi v0.3.9
   Compiling vcpkg v0.2.15
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling windows_x86_64_msvc v0.52.0
   Compiling libc v0.2.153
   Compiling rustversion v1.0.14
   Compiling typenum v1.17.0
   Compiling log v0.4.20
   Compiling once_cell v1.19.0
   Compiling memchr v2.7.1
   Compiling unicode-xid v0.2.4
   Compiling zerocopy v0.7.32
   Compiling thiserror v1.0.57
   Compiling parking_lot_core v0.9.9
   Compiling subtle v2.5.0
   Compiling tinyvec_macros v0.1.1
   Compiling serde_json v1.0.113
   Compiling scopeguard v1.2.0
   Compiling crunchy v0.2.2
   Compiling allocator-api2 v0.2.16
   Compiling regex-syntax v0.8.2
   Compiling cc v1.0.83
   Compiling smallvec v1.13.1
   Compiling hip_runtime-sys v0.0.0 (E:\ML\zluda\hip_runtime-sys)
   Compiling tinyvec v1.6.0
   Compiling ryu v1.0.16
   Compiling siphasher v0.3.11
   Compiling rustc-hash v1.1.0
   Compiling itoa v1.0.10
   Compiling ahash v0.8.8
   Compiling generic-array v0.14.7
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling lock_api v0.4.11
   Compiling aho-corasick v1.1.2
   Compiling cmake v0.1.50
   Compiling tiny-keccak v2.0.2
   Compiling equivalent v1.0.1
   Compiling libsqlite3-sys v0.25.2
   Compiling libz-sys v1.1.15
   Compiling anyhow v1.0.79
   Compiling bitflags v1.3.2
   Compiling convert_case v0.5.0
   Compiling phf_shared v0.10.0
   Compiling libgit2-sys v0.14.2+1.5.1
   Compiling unicode-normalization v0.1.22
   Compiling regex-automata v0.4.5
   Compiling percent-encoding v2.3.1
   Compiling windows-targets v0.48.5
   Compiling fallible-streaming-iterator v0.1.9
   Compiling bit-vec v0.6.3
   Compiling either v1.10.0
   Compiling windows-targets v0.52.0
   Compiling fallible-iterator v0.2.0
   Compiling llvm-sys v150.1.2 (E:\ML\zluda\ext\llvm-sys.rs)
   Compiling unicode-bidi v0.3.15
   Compiling time-core v0.1.1
   Compiling libm v0.2.8
   Compiling new_debug_unreachable v1.0.4
   Compiling precomputed-hash v0.1.1
   Compiling cpufeatures v0.2.12
   Compiling windows-sys v0.52.0
   Compiling windows-sys v0.48.0
   Compiling plain v0.2.3
   Compiling fixedbitset v0.4.2
   Compiling bit-set v0.5.3
   Compiling itertools v0.10.5
   Compiling form_urlencoded v1.2.1
   Compiling quote v1.0.35
   Compiling regex v1.10.3
   Compiling lz4-sys v1.9.4
   Compiling dirs-sys-next v0.1.2
   Compiling num-traits v0.2.18
   Compiling time v0.3.23
   Compiling idna v0.5.0
   Compiling ena v0.14.2
   Compiling diff v0.1.13
   Compiling paste v1.0.14
   Compiling regex-syntax v0.7.5
   Compiling capnp v0.17.2
   Compiling syn v2.0.48
   Compiling hashbrown v0.14.3
   Compiling parking_lot v0.12.1
   Compiling pico-args v0.5.0
   Compiling const_format_proc_macros v0.2.32
   Compiling lalrpop-util v0.20.0
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling libloading v0.8.1
   Compiling dirs-next v2.0.0
   Compiling detours-sys v0.1.2 (E:\ML\zluda\detours-sys)
   Compiling zluda_llvm v0.0.0 (E:\ML\zluda\zluda_llvm)
   Compiling bitflags v2.4.2
   Compiling indexmap v2.2.3
   Compiling is-terminal v0.4.12
   Compiling hashlink v0.8.4
   Compiling url v2.5.0
   Compiling digest v0.10.7
   Compiling term v0.7.0
   Compiling cpp_demangle v0.3.5
   Compiling proc-macro-hack v0.5.20+deprecated
   Compiling string_cache v0.8.7
   Compiling thread-id v4.2.1
   Compiling vergen v7.5.1
   Compiling blake3 v1.3.3
   Compiling const_format v0.2.32
   Compiling memoffset v0.8.0
   Compiling serde_derive v1.0.196
   Compiling scroll_derive v0.11.1
   Compiling thiserror-impl v1.0.57
   Compiling enum-iterator-derive v1.3.0
   Compiling crossbeam-utils v0.8.19
   Compiling sha2 v0.10.8
   Compiling fastrand v2.0.1
   Compiling dirs-sys v0.3.7
   Compiling lazy_static v1.4.0
   Compiling atiadlxx-sys v0.0.0 (E:\ML\zluda\atiadlxx-sys)
   Compiling embed-manifest v1.4.0
   Compiling petgraph v0.6.4
   Compiling cuda_base v0.0.0 (E:\ML\zluda\cuda_base)
   Compiling derivative v2.2.0
   Compiling arrayref v0.3.7
   Compiling ascii-canvas v3.0.0
   Compiling byteorder v1.5.0
   Compiling constant_time_eq v0.2.6
   Compiling arrayvec v0.7.4
   Compiling dirs v4.0.0
   Compiling static_assertions v1.1.0
   Compiling scroll v0.11.0
   Compiling memmap2 v0.5.10
   Compiling getset v0.1.2
   Compiling enum-iterator v1.5.0
   Compiling zluda_inject v0.0.0 (E:\ML\zluda\zluda_inject)
   Compiling tempfile v3.10.0
   Compiling half v1.8.2
   Compiling cuda_types v0.0.0 (E:\ML\zluda\cuda_types)
   Compiling lalrpop v0.20.0
   Compiling dynasm v1.2.3
   Compiling crossbeam-channel v0.5.11
   Compiling wchar-impl v0.6.0
   Compiling goblin v0.5.4
   Compiling zluda_ml v0.0.0 (E:\ML\zluda\zluda_ml)
   Compiling wchar v0.6.1
   Compiling zluda_redirect v0.0.0 (E:\ML\zluda\zluda_redirect)
   Compiling toml v0.5.11
   Compiling argh_shared v0.1.12
   Compiling argh_derive v0.1.12
   Compiling proc-macro-crate v0.1.5
   Compiling rusqlite v0.28.0
   Compiling argh v0.1.12
   Compiling num_enum_derive v0.4.3
   Compiling num_enum v0.4.3
   Compiling dynasmrt v1.2.3
   Compiling hip_common v0.0.0 (E:\ML\zluda\hip_common)
   Compiling zluda_dark_api v0.0.0 (E:\ML\zluda\zluda_dark_api)
   Compiling comgr v0.0.0 (E:\ML\zluda\comgr)
   Compiling git2 v0.16.1
   Compiling ptx v0.0.0 (E:\ML\zluda\ptx)
   Compiling zluda v0.0.0 (E:\ML\zluda\zluda)
error: failed to run custom build command for `llvm-sys v150.1.2 (E:\ML\zluda\ext\llvm-sys.rs)`

Caused by:
  process didn't exit successfully: `E:\ML\zluda\target\release\build\llvm-sys-13924a98eaab7d91\build-script-build` (exit code: 101)
  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
    The OLD behavior for policy CMP0114 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
    The OLD behavior for policy CMP0116 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  CMake Warning at E:/ML/zluda/ext/llvm-project/third-party/benchmark/CMakeLists.txt:308 (message):
    Using std::regex with exceptions disabled is not fully supported


  thread 'main' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\xtask.exe --release` (exit code: 101)
```

**Comment by lshqqytiger** [comment]
Downgraded rust to 1.66.1, I got
```
error: package `ahash v0.8.8` cannot be built because it requires rustc 1.72.0 or newer, while the currently active rustc version is 1.66.1
```
Upgraded 1.66.1 -> 1.72.0, I got same error with my previous post.

**Comment by lshqqytiger** [comment]
With traceback:
```
error: failed to run custom build command for `llvm-sys v150.1.2 (E:\ML\zluda\ext\llvm-sys.rs)`

Caused by:
  process didn't exit successfully: `E:\ML\zluda\target\release\build\llvm-sys-23a1a7a99206415b\build-script-build` (exit code: 101)
  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
    The OLD behavior for policy CMP0114 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
    The OLD behavior for policy CMP0116 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  CMake Warning at E:/ML/zluda/ext/llvm-project/third-party/benchmark/CMakeLists.txt:308 (message):
    Using std::regex with exceptions disabled is not fully supported


  thread 'main' panicked at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\std\src\panicking.rs:645
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library\core\src\panicking.rs:72
     2: cmake::fail
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098
     3: cmake::run
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1076
     4: cmake::Config::build
               at C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:874
     5: build_script_build::build_cmake_targets<core::iter::adapters::map::Map<core::slice::iter::Iter<ref$<str$> >,build_script_build::main::closure_env$0> >
               at .\build.rs:56
     6: build_script_build::main
               at .\build.rs:20
     7: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\ops\function.rs:250
     8: core::hint::black_box
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce\library\core\src\hint.rs:286
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\xtask.exe --release` (exit code: 101)
```

**Comment by vosen** [comment]
It's failing somewhere in LLVM compilation. Not sure what the problem is, but my suggestions:
- Make sure that you have all the depndencies (recent version of MSVC C++ compiler, Python 3)
- In case of failed compilation CMake usually leaves a text log, look for one in `E:\ML\zluda\target\release`
- Try running from x64 Native Tools Command Prompt for VS XX
- Add `.very_verbose(true)` line below `.always_configure(true)` in `zluda\ext\llvm-sys.rs\build.rs` this might produce more debug information
- Try building `ext\llvm-project` independently (instructions here: https://llvm.org/docs/CMake.html)

**Comment by lshqqytiger** [comment]
I have MSVC v143 - VS 2022 compiler, Windows 11 SDK (10.0.22621.0) and Python 3.10.13.
Tried Developer Power Shell for VS 2022, same error.
Added `.very_verbose(true)`: [log.txt](https://github.com/vosen/ZLUDA/files/14269801/log.txt)
I built `ext\llvm-project` independently. How can I make llvm-sys.rs to use it?

**Comment by vosen** [comment]
Hmmm, wrangling ZLUDA to use independently compiled LLVM might be tricky. You'd need to modify `zluda\ext\llvm-sys.rs\build.rs` and `zluda\zluda_llvm\build.rs` to pick up the libraries at those paths and not rebuild.

It looks like your build is dying in unexplained circumstances. I have one more idea. Try procmon from sysinternals suite. Setup it to filter "Process Start" and "Process Exit" like that: 
![Screenshot 2024-02-13 213856](https://github.com/vosen/ZLUDA/assets/1206376/6cb9dc54-735f-4605-8079-f74b1ceb2354) It will capture system-wide so better close other applications. You should see the list fill up with start&stop of cmake.exe, rustc.exe, link.exe, python.exe, rc.exe and related. Check what process is exiting with non-0 status.


BTW, for anyone reading this, it may seem that ZLUDA is building its own LLVM just to make everyone's life a little bit harder, but there are actually good reasons for that:
- ZLUDA acceses LLVM through stable LLVM C API, but that API misses a handful of key features
- ZLUDA does not build whole LLVM, but just a subset that is necessary to emit LLVM IR, making builds faster and binaries smaller
- We need to control LLVM version so we emit supported LLVM IR

**Comment by emilmasoumi** [comment]
Clone the LLVM project repository into the `ext/llvm-project/` directory:

```bash
$ # Assuming that the current working directory is `ZLUDA`.
$ git clone https://github.com/llvm/llvm-project ext/llvm-project/
```

**Comment by lshqqytiger** [comment]
Executable: `E:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe`
Module: `E:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\c2.dll`
MSVC is exiting with non-0 status.
The exception code is `0xc0000005` or `0xc000001d`.

**Comment by lshqqytiger** [comment]
![image](https://github.com/vosen/ZLUDA/assets/39524005/b13a2e0b-6395-409e-bcd9-4bc4c68712a7)
![image](https://github.com/vosen/ZLUDA/assets/39524005/5085242a-e2e4-4737-9383-3ae66e85c803)
I found Windows Hardware Errors Architecture captured a hardware error occurred.
As I know, CPU L0 cache error is mostly due to system memory.

**Comment by lshqqytiger** [comment]
Okay. I successfully built ZLUDA.

My system info:
Intel Core i9-14900K
SAMSUNG DDR5 5600MHz 32GBx4

Even I didn't overclocked my cpu and memory, I have to down-clock them.
I disabled E-core of my cpu and down-clocked cpu to up to 3000MHz.
I down-clocked my memory to **1200MHz**. (2400MHz didn't help)
Thank you for help.

**Comment by ceewanna** [comment]
I have this problem.
`ZLUDA/ext/llvm-project/llvm does not exist`

It seems https://rocm.docs.amd.com/projects/install-on-linux/en/latest/ is catered for Ubuntu while mine is Debian. Anyone has work around for this please?

**Comment by lshqqytiger** [comment]
I'm on different environment and had different cause. You can open another issue yourself.
